anadarko2postgre_awac_temp.py CM13_ADCP_temp_P5toP6.csv  101 adcp
anadarko2postgre_awac_temp.py CM15_ADCP_temp_P5toP6.csv  103 adcp
anadarko2postgre_awac_temp.py CM16_ADCP_temp_P5toP6.csv  104 adcp

anadarko2postgre_awac_temp.py CM10_ADCP_temperature_P2.csv  99 adcp
anadarko2postgre_awac_temp.py CM10_ADCP_temperature_P4.csv 118 adcp
anadarko2postgre_awac_temp.py CM10_ADCP_temp_P5.csv 118 adcp
anadarko2postgre_awac_temp.py CM10_ADCP_temp_P6.csv  37 adcp
anadarko2postgre_awac_temp.py CM10_ADCP_temp_P6_2.csv  53 adcp
anadarko2postgre_awac_temp.py CM11_ADCP_temperature_P1.csv  86 adcp
anadarko2postgre_awac_temp.py CM11_ADCP_temperature_P2.csv 118 adcp
anadarko2postgre_awac_temp.py CM11_ADCP_temperature_P4.csv 134 adcp
anadarko2postgre_awac_temp.py CM11_ADCP_temp_P6.csv  38 adcp
anadarko2postgre_awac_temp.py CM11_ADCP_temp_P7.csv  54 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temperature_P1.csv  87 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temperature_P2.csv 100 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temperaure_P4.csv 119 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temp_P5.csv 135 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temp_P6.csv  72 adcp
anadarko2postgre_awac_temp.py CM12_ADCP_temp_P7.csv  73 adcp
anadarko2postgre_awac_temp.py CM13_ADCP_temperature_P3_Loc1.csv  74 adcp
anadarko2postgre_awac_temp.py CM13_ADCP_temperature_P3_Loc2.csv  88 adcp
anadarko2postgre_awac_temp.py CM13_ADCP_temperature_P3_Loc3.csv  32 adcp
anadarko2postgre_awac_temp.py CM13_ADCP_temperature_P4.csv  48 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temperature_P3_Loc1.csv  64 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temperature_P3_Loc2.csv  65 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temperature_P4.csv  82 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temp_P5.csv  96 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temp_P6.csv 114 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temp_P6_2.csv 114 adcp
anadarko2postgre_awac_temp.py CM6_ADCP_temp_P7.csv 130 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temperature_P1.csv  34 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temperature_P2.csv  50 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temperature_P4.csv  83 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temp_P5.csv  97 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temp_P6.csv 115 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temp_P6_2.csv 115 adcp
anadarko2postgre_awac_temp.py CM8_ADCP_temp_P7.csv 131 adcp
anadarko2postgre_awac_temp.py CM15_ADCP_temp_P7.csv 137 adcp
anadarko2postgre_awac_temp.py CM16_ADCP_temp_P7.csv 138 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temperature_P1.csv  35 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temperature_P2.csv  51 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temperature_P4.csv  84 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temp_P5.csv  98 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temp_P6.csv 116 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temp_P6_2.csv 116 adcp
anadarko2postgre_awac_temp.py CM9_ADCP_temp_P7.csv 132 adcp